export const task_obj = {
    "output": [
    {
        "ASAPOL88": [
            {
                "SevOne": {
                    "status": "Success",
                    "result": [
                        {
                            "name": "ASAPOL88",
                            "snmpTestOid": ".1.3.6.1.2.1.1.1.0",
                            "numElements": 56,
                            "snmpVersion": "2",
                            "snmpPort": "161",
                            "ipAddress": "10.253.38.18"
                        }
                    ]
                }
            },
            {
                "NEST": {
                    "status": "Success",
                    "result": [
                        {
                            "b:ModifiedDate": "2016-06-02T19:15:36.82",
                            "b:ToStateDescription": "InService",
                            "b:SystemName": "All Systems",
                            "b:Notes": "CR#2535786 - ASAPOL88 - Accepted into Production by Tier 2 IP Deployment Projects",
                            "b:NextStateDescription": null,
                            "b:TechnologyDescription": "Other",
                            "b:StateChangeStatusDescription": "Completed"
                        }
                    ]
                }
            },
            {
                "MFNA (CIAO)": {
                    "status": "Success",
                    "result": [
                        {
                            "lastSnapshotDate": "Wed Dec 11 09:11:12 PST 2019",
                            "lastSnapshotAttemptStatus": "Configuration unchanged",
                            "siteName": "Default Site",
                            "ip": "10.253.38.18",
                            "hostName": "ASAPOL88",
                            "lastConfigPolicyCheckedDate": "Mon Feb 03 21:00:31 PST 2020",
                            "NAStatus": "501",
                            "createDate": "Wed Apr 17 20:35:47 PDT 2019",
                            "lastSnapshotAttemptDate": "Mon Feb 03 12:31:46 PST 2020",
                            "vendor": "Cisco",
                            "freePorts": "12",
                            "deviceType": "Switch",
                            "lastAccessAttemptStatus": "Run Diagnostics: Task run",
                            "lastAccessSuccessDate": "Mon Feb 03 17:19:55 PST 2020",
                            "lastImportDate": "Wed Apr 17 20:35:47 PDT 2019",
                            "deviceAcceptanceStatus": "Yes",
                            "lastAccessAttemptDate": "Mon Feb 03 17:19:55 PST 2020",
                            "lastSnapshotSuccessDate": "Mon Feb 03 12:31:46 PST 2020",
                            "accessMethods": "SNMP:CLI+commstr:ssh",
                            "softwareVersion": "7.0(3)I7(6)",
                            "contact": "TierII IP Support 1-866-783-9557 Option 4",
                            "driverName": "CiscoNexus",
                            "model": "Nexus3000 C3064PQ",
                            "totalPorts": "52"
                        }
                    ]
                }
            },
            {
                "MFNA (CIAO))": {
                    "status": "Error",
                    "result": [
                        {}
                    ],
                    "error": "list indices must be integers, not str"
                }
            },
            {
                "OneConsole Alarms (CIAO)": {
                    "status": "Success",
                    "result": [
                        {
                            "Alarm 0": {
                                "display_date": 1578330584000,
                                "kms_assignee_group": null,
                                "oneconsole_unique_id": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "assignee": null,
                                "ttid": null,
                                "app_name": "AccessSwitch_Applications",
                                "kms_sys_id": null,
                                "appdalarmid": null,
                                "platform": null,
                                "latitude": "47.40686",
                                "message_number": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "predictive_child_ind": null,
                                "delay_on_generate": null,
                                "viewtype": "NOC",
                                "time_last_rcvd": 1578330584000,
                                "time_unbuffered": null,
                                "neregioncode": "CORPORATE",
                                "ola": null,
                                "ack_date": null,
                                "networkelementcode": "ASAPOL88",
                                "alertid": "201133188",
                                "source_table": null,
                                "manager_name": "ASAPOL88.MGMT",
                                "amoclass": null,
                                "omtemplsource": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "ssparentgrp": null,
                                "kpi_ind": null,
                                "marketcode": "OC",
                                "forwarding_mgr": "omimcsb.tt.t-mobile.com",
                                "technology": "IP",
                                "message_key": "EventLifecycleStateClosed (SNMPv1):ASAPOL88.MGMT:bb1a1dac-35f9-46c9-a9f7-4e01f9996a79_AutoAck_AutoAck",
                                "autoticket": null,
                                "kms_description_action": null,
                                "goldengate_datasource_id": "55",
                                "cleared_date": 1578330584000,
                                "fwd_to_oneconsole_unique_id": null,
                                "clearing_reason": null,
                                "delay_rule": null,
                                "amoname": "ASAPOL88::Ethernet1/5",
                                "alarm_inservice_date": 1578330584000,
                                "pool_id": null,
                                "kms_clearalarm": null,
                                "manager_class": "AccessSwitch_Applications",
                                "created_date": 1578330584000,
                                "cleared_by": null,
                                "sequence_no": "7",
                                "standard_msg_created_date": 1578330583000,
                                "kms_description": null,
                                "alert_no": null,
                                "update_date": 1578330591935,
                                "element_class": "SWITCH",
                                "system": "OMI",
                                "priority": null,
                                "kms_severity": null,
                                "notification_level": null,
                                "time_first_rcvd": 1578330584000,
                                "subscription": null,
                                "standard_msg_app_name": "OMI",
                                "longitude": "-120.1886",
                                "host_site_cd": null,
                                "parent_ind": null,
                                "kms_assignee": null,
                                "message_source": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "standard_msg_unique_id": null,
                                "severity": "NORMAL",
                                "knowledge_ind_update_date": null,
                                "message_grp": "SNMP",
                                "incidentid": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "port_id": null,
                                "time_owned": null,
                                "last_one": null,
                                "alarm_count": "0",
                                "alert_name": "EventLifecycleStateClosed",
                                "application": "NNMi",
                                "ring_cd_category": null,
                                "ring_cd_description": null,
                                "knowledge_ind": "X",
                                "alarm_source_delay_display": null,
                                "update_source": "2",
                                "ack_oper": null,
                                "available_knowledge_indicators": null,
                                "description": "Event (SNMPLinkUp,bb1a1dac-35f9-46c9-a9f7-4e01f9996a79) is closed. ASAPOL88.MGMT:com.hp.ov.nms.model.core.Interface=Ethernet1/5",
                                "standard_msg_parent_id": "ASAPOL88__IP",
                                "object": "Ethernet1/5",
                                "vendor_code": "CISCO",
                                "nesm": "InService",
                                "ticket_status": null,
                                "child_ind": null,
                                "first_nesm": "InService",
                                "forwarding_sys": "IPAlarming.tt",
                                "clearing_reason_id": null,
                                "market_flood_flag": null
                            },
                            "Alarm 1": {
                                "display_date": 1578330584000,
                                "kms_assignee_group": null,
                                "oneconsole_unique_id": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "assignee": null,
                                "ttid": null,
                                "app_name": "AccessSwitch_Applications",
                                "kms_sys_id": null,
                                "appdalarmid": null,
                                "platform": null,
                                "latitude": "47.40686",
                                "message_number": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "predictive_child_ind": null,
                                "delay_on_generate": null,
                                "viewtype": "NOC",
                                "time_last_rcvd": 1578330584000,
                                "time_unbuffered": null,
                                "neregioncode": "CORPORATE",
                                "ola": null,
                                "ack_date": null,
                                "networkelementcode": "ASAPOL88",
                                "alertid": "201133188",
                                "source_table": null,
                                "manager_name": "ASAPOL88.MGMT",
                                "amoclass": null,
                                "omtemplsource": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "ssparentgrp": null,
                                "kpi_ind": null,
                                "marketcode": "OC",
                                "forwarding_mgr": "omimcsb.tt.t-mobile.com",
                                "technology": "IP",
                                "message_key": "EventLifecycleStateClosed (SNMPv1):ASAPOL88.MGMT:bb1a1dac-35f9-46c9-a9f7-4e01f9996a79_AutoAck_AutoAck",
                                "autoticket": null,
                                "kms_description_action": null,
                                "goldengate_datasource_id": "55",
                                "cleared_date": 1578330584000,
                                "fwd_to_oneconsole_unique_id": null,
                                "clearing_reason": null,
                                "delay_rule": null,
                                "amoname": "ASAPOL88::Ethernet1/5",
                                "alarm_inservice_date": 1578330584000,
                                "pool_id": null,
                                "kms_clearalarm": null,
                                "manager_class": "AccessSwitch_Applications",
                                "created_date": 1578330584000,
                                "cleared_by": null,
                                "sequence_no": "7",
                                "standard_msg_created_date": 1578330583000,
                                "kms_description": null,
                                "alert_no": null,
                                "update_date": 1578330591935,
                                "element_class": "SWITCH",
                                "system": "OMI",
                                "priority": null,
                                "kms_severity": null,
                                "notification_level": null,
                                "time_first_rcvd": 1578330584000,
                                "subscription": null,
                                "standard_msg_app_name": "OMI",
                                "longitude": "-120.1886",
                                "host_site_cd": null,
                                "parent_ind": null,
                                "kms_assignee": null,
                                "message_source": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "standard_msg_unique_id": null,
                                "severity": "NORMAL",
                                "knowledge_ind_update_date": null,
                                "message_grp": "SNMP",
                                "incidentid": "557a0e5e-30a7-71ea-1630-0a8b0c100000",
                                "port_id": null,
                                "time_owned": null,
                                "last_one": null,
                                "alarm_count": "0",
                                "alert_name": "EventLifecycleStateClosed",
                                "application": "NNMi",
                                "ring_cd_category": null,
                                "ring_cd_description": null,
                                "knowledge_ind": "X",
                                "alarm_source_delay_display": null,
                                "update_source": "2",
                                "ack_oper": null,
                                "available_knowledge_indicators": null,
                                "description": "Event (SNMPLinkUp,bb1a1dac-35f9-46c9-a9f7-4e01f9996a79) is closed. ASAPOL88.MGMT:com.hp.ov.nms.model.core.Interface=Ethernet1/5",
                                "standard_msg_parent_id": "ASAPOL88__IP",
                                "object": "Ethernet1/5",
                                "vendor_code": "CISCO",
                                "nesm": "InService",
                                "ticket_status": null,
                                "child_ind": null,
                                "first_nesm": "InService",
                                "forwarding_sys": "IPAlarming.tt",
                                "clearing_reason_id": null,
                                "market_flood_flag": null
                            },
                            "Alarm 2": {
                                "display_date": 1578330584000,
                                "kms_assignee_group": null,
                                "oneconsole_unique_id": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "assignee": null,
                                "ttid": null,
                                "app_name": "AccessSwitch_Applications",
                                "kms_sys_id": null,
                                "appdalarmid": null,
                                "platform": null,
                                "latitude": "47.40686",
                                "message_number": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "predictive_child_ind": null,
                                "delay_on_generate": null,
                                "viewtype": "NOC",
                                "time_last_rcvd": 1578330584000,
                                "time_unbuffered": null,
                                "neregioncode": "CORPORATE",
                                "ola": null,
                                "ack_date": null,
                                "networkelementcode": "ASAPOL88",
                                "alertid": "201133187",
                                "source_table": null,
                                "manager_name": "ASAPOL88.MGMT",
                                "amoclass": null,
                                "omtemplsource": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "ssparentgrp": null,
                                "kpi_ind": null,
                                "marketcode": "OC",
                                "forwarding_mgr": "omimcsb.tt.t-mobile.com",
                                "technology": "IP",
                                "message_key": "EventLifecycleStateClosed (SNMPv1):ASAPOL88.MGMT:ee0c2e49-c8ef-4077-90c2-159faa7bcd99_AutoAck_AutoAck",
                                "autoticket": null,
                                "kms_description_action": null,
                                "goldengate_datasource_id": "55",
                                "cleared_date": 1578330584000,
                                "fwd_to_oneconsole_unique_id": null,
                                "clearing_reason": null,
                                "delay_rule": null,
                                "amoname": "ASAPOL88::Ethernet1/5",
                                "alarm_inservice_date": 1578330584000,
                                "pool_id": null,
                                "kms_clearalarm": null,
                                "manager_class": "AccessSwitch_Applications",
                                "created_date": 1578330584000,
                                "cleared_by": null,
                                "sequence_no": "7",
                                "standard_msg_created_date": 1578330583000,
                                "kms_description": null,
                                "alert_no": null,
                                "update_date": 1578330591915,
                                "element_class": "SWITCH",
                                "system": "OMI",
                                "priority": null,
                                "kms_severity": null,
                                "notification_level": null,
                                "time_first_rcvd": 1578330584000,
                                "subscription": null,
                                "standard_msg_app_name": "OMI",
                                "longitude": "-120.1886",
                                "host_site_cd": null,
                                "parent_ind": null,
                                "kms_assignee": null,
                                "message_source": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "standard_msg_unique_id": null,
                                "severity": "NORMAL",
                                "knowledge_ind_update_date": null,
                                "message_grp": "SNMP",
                                "incidentid": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "port_id": null,
                                "time_owned": null,
                                "last_one": null,
                                "alarm_count": "0",
                                "alert_name": "EventLifecycleStateClosed",
                                "application": "NNMi",
                                "ring_cd_category": null,
                                "ring_cd_description": null,
                                "knowledge_ind": "X",
                                "alarm_source_delay_display": null,
                                "update_source": "2",
                                "ack_oper": null,
                                "available_knowledge_indicators": null,
                                "description": "Event (SNMPLinkDown,ee0c2e49-c8ef-4077-90c2-159faa7bcd99) is closed. ASAPOL88.MGMT:com.hp.ov.nms.model.core.Interface=Ethernet1/5",
                                "standard_msg_parent_id": "ASAPOL88__IP",
                                "object": "Ethernet1/5",
                                "vendor_code": "CISCO",
                                "nesm": "InService",
                                "ticket_status": null,
                                "child_ind": null,
                                "first_nesm": "InService",
                                "forwarding_sys": "IPAlarming.tt",
                                "clearing_reason_id": null,
                                "market_flood_flag": null
                            },
                            "Alarm 3": {
                                "display_date": 1578330584000,
                                "kms_assignee_group": null,
                                "oneconsole_unique_id": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "assignee": null,
                                "ttid": null,
                                "app_name": "AccessSwitch_Applications",
                                "kms_sys_id": null,
                                "appdalarmid": null,
                                "platform": null,
                                "latitude": "47.40686",
                                "message_number": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "predictive_child_ind": null,
                                "delay_on_generate": null,
                                "viewtype": "NOC",
                                "time_last_rcvd": 1578330584000,
                                "time_unbuffered": null,
                                "neregioncode": "CORPORATE",
                                "ola": null,
                                "ack_date": null,
                                "networkelementcode": "ASAPOL88",
                                "alertid": "201133187",
                                "source_table": null,
                                "manager_name": "ASAPOL88.MGMT",
                                "amoclass": null,
                                "omtemplsource": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "ssparentgrp": null,
                                "kpi_ind": null,
                                "marketcode": "OC",
                                "forwarding_mgr": "omimcsb.tt.t-mobile.com",
                                "technology": "IP",
                                "message_key": "EventLifecycleStateClosed (SNMPv1):ASAPOL88.MGMT:ee0c2e49-c8ef-4077-90c2-159faa7bcd99_AutoAck_AutoAck",
                                "autoticket": null,
                                "kms_description_action": null,
                                "goldengate_datasource_id": "55",
                                "cleared_date": 1578330584000,
                                "fwd_to_oneconsole_unique_id": null,
                                "clearing_reason": null,
                                "delay_rule": null,
                                "amoname": "ASAPOL88::Ethernet1/5",
                                "alarm_inservice_date": 1578330584000,
                                "pool_id": null,
                                "kms_clearalarm": null,
                                "manager_class": "AccessSwitch_Applications",
                                "created_date": 1578330584000,
                                "cleared_by": null,
                                "sequence_no": "7",
                                "standard_msg_created_date": 1578330583000,
                                "kms_description": null,
                                "alert_no": null,
                                "update_date": 1578330591915,
                                "element_class": "SWITCH",
                                "system": "OMI",
                                "priority": null,
                                "kms_severity": null,
                                "notification_level": null,
                                "time_first_rcvd": 1578330584000,
                                "subscription": null,
                                "standard_msg_app_name": "OMI",
                                "longitude": "-120.1886",
                                "host_site_cd": null,
                                "parent_ind": null,
                                "kms_assignee": null,
                                "message_source": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "standard_msg_unique_id": null,
                                "severity": "NORMAL",
                                "knowledge_ind_update_date": null,
                                "message_grp": "SNMP",
                                "incidentid": "55755da0-30a7-71ea-1630-0a8b0c100000",
                                "port_id": null,
                                "time_owned": null,
                                "last_one": null,
                                "alarm_count": "0",
                                "alert_name": "EventLifecycleStateClosed",
                                "application": "NNMi",
                                "ring_cd_category": null,
                                "ring_cd_description": null,
                                "knowledge_ind": "X",
                                "alarm_source_delay_display": null,
                                "update_source": "2",
                                "ack_oper": null,
                                "available_knowledge_indicators": null,
                                "description": "Event (SNMPLinkDown,ee0c2e49-c8ef-4077-90c2-159faa7bcd99) is closed. ASAPOL88.MGMT:com.hp.ov.nms.model.core.Interface=Ethernet1/5",
                                "standard_msg_parent_id": "ASAPOL88__IP",
                                "object": "Ethernet1/5",
                                "vendor_code": "CISCO",
                                "nesm": "InService",
                                "ticket_status": null,
                                "child_ind": null,
                                "first_nesm": "InService",
                                "forwarding_sys": "IPAlarming.tt",
                                "clearing_reason_id": null,
                                "market_flood_flag": null
                            },
                            "Alarm 4": {
                                "display_date": 1578330405000,
                                "kms_assignee_group": null,
                                "oneconsole_unique_id": "ea7cf92c-30a6-71ea-1630-0a8b0c100000",
                                "assignee": null,
                                "ttid": null,
                                "app_name": "AccessSwitch_Applications",
                                "kms_sys_id": null,
                                "appdalarmid": null,
                                "platform": null,
                                "latitude": "47.40686",
                                "message_number": "ea7cf92c-30a6-71ea-1630-0a8b0c100000",
                                "predictive_child_ind": null,
                                "delay_on_generate": null,
                                "viewtype": "NOC",
                                "time_last_rcvd": 1578330405000,
                                "time_unbuffered": null,
                                "neregioncode": "CORPORATE",
                                "ola": null,
                                "ack_date": null,
                                "networkelementcode": "ASAPOL88",
                                "alertid": "201133032",
                                "source_table": null,
                                "manager_name": "ASAPOL88.MGMT",
                                "amoclass": null,
                                "omtemplsource": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "ssparentgrp": null,
                                "kpi_ind": null,
                                "marketcode": "OC",
                                "forwarding_mgr": "omimcsb.tt.t-mobile.com",
                                "technology": "IP",
                                "message_key": "EventLifecycleStateClosed (SNMPv1):ASAPOL88.MGMT:6dc564ab-b264-45a3-87ee-599452a2fba5_AutoAck_AutoAck",
                                "autoticket": null,
                                "kms_description_action": null,
                                "goldengate_datasource_id": "55",
                                "cleared_date": 1578330405000,
                                "fwd_to_oneconsole_unique_id": null,
                                "clearing_reason": null,
                                "delay_rule": null,
                                "amoname": "ASAPOL88::Ethernet1/5",
                                "alarm_inservice_date": 1578330405000,
                                "pool_id": null,
                                "kms_clearalarm": null,
                                "manager_class": "AccessSwitch_Applications",
                                "created_date": 1578330405000,
                                "cleared_by": null,
                                "sequence_no": "7",
                                "standard_msg_created_date": 1578330404000,
                                "kms_description": null,
                                "alert_no": null,
                                "update_date": 1578330415020,
                                "element_class": "SWITCH",
                                "system": "OMI",
                                "priority": null,
                                "kms_severity": null,
                                "notification_level": null,
                                "time_first_rcvd": 1578330405000,
                                "subscription": null,
                                "standard_msg_app_name": "OMI",
                                "longitude": "-120.1886",
                                "host_site_cd": null,
                                "parent_ind": null,
                                "kms_assignee": null,
                                "message_source": "tm_new_NNMi2OM(1.42)||EventLifecycleStateClosed (SNMPv1)",
                                "standard_msg_unique_id": null,
                                "severity": "NORMAL",
                                "knowledge_ind_update_date": null,
                                "message_grp": "SNMP",
                                "incidentid": "ea7cf92c-30a6-71ea-1630-0a8b0c100000",
                                "port_id": null,
                                "time_owned": null,
                                "last_one": null,
                                "alarm_count": "0",
                                "alert_name": "EventLifecycleStateClosed",
                                "application": "NNMi",
                                "ring_cd_category": null,
                                "ring_cd_description": null,
                                "knowledge_ind": "X",
                                "alarm_source_delay_display": null,
                                "update_source": "2",
                                "ack_oper": null,
                                "available_knowledge_indicators": null,
                                "description": "Event (SNMPLinkUp,6dc564ab-b264-45a3-87ee-599452a2fba5) is closed. ASAPOL88.MGMT:com.hp.ov.nms.model.core.Interface=Ethernet1/5",
                                "standard_msg_parent_id": "ASAPOL88__IP",
                                "object": "Ethernet1/5",
                                "vendor_code": "CISCO",
                                "nesm": "InService",
                                "ticket_status": null,
                                "child_ind": null,
                                "first_nesm": "InService",
                                "forwarding_sys": "IPAlarming.tt",
                                "clearing_reason_id": null,
                                "market_flood_flag": null
                            }
                        }
                    ]
                }
            },
            {
                "DNS": {
                    "status": "Success",
                    "result": [
                        {
                            "ip_address": "10.253.38.18",
                            "names": [
                                "asapol88_mgmt.nmnet"
                            ],
                            "network_view": "NMNET"
                        }
                    ]
                }
            },
            {
                "EAI": {
                    "status": "Success",
                    "result": [
                        {
                            "status": "In Service",
                            "vendor": "CISCO",
                            "shelf": "42",
                            "clli": "EWNCWADT",
                            "model": "NEXUS 3064-X",
                            "rack": "08",
                            "row": "117"
                        }
                    ]
                }
            },
            {
                "EAI Paths": {
                    "status": "Success",
                    "result": [
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-31\\WSGPOL63_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-10\\NPAPOL31_IOR-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-11\\NPAPOL32_IOR-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-47\\NPAPOL15_NIC2",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-7\\NPAPOL16_IOR-1-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-8\\NPAPOL17_IOR-1-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-5\\NPAPOL11_IOR-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-9\\NPAPOL30_IOR-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-45\\NPAPOL31_ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-5\\NPAPOL11_LOM1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-37\\WSGPOL58_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-42\\WSGPOL57_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-36\\WSGPOL57_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-48\\NPAPOL11_ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-28\\WSGPOL70_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-32\\WSGPOL65_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-21\\WSGPOL63_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-22\\WSGPOL64_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-23\\WSGPOL65_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-34\\WSGPOL69_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-27\\WSGPOL69_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-30\\WSGPOL72_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-26\\WSGPOL68_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-35\\WSGPOL71_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-29\\WSGPOL71_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-24\\WSGPOL66_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-33\\WSGPOL67_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-25\\WSGPOL67_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-6\\NPAPOL12_IOR-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-39\\WSGPOL60_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-40\\WSGPOL61_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-41\\WSGPOL62_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-46\\NPAPOL17_ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "10GbE",
                            "path": "ASAPOL88_E1-12\\NPAPOL15_PCI1-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-44\\WSGPOL61_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-43\\WSGPOL59_IO-R-ILO",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        },
                        {
                            "status": "In Service",
                            "aSideSite": "POLARIS DATACENTER",
                            "host": "ASAPOL88",
                            "bandWidth": "GbE",
                            "path": "ASAPOL88_E1-38\\WSGPOL59_IO-R-NIC-1",
                            "zSideSite": "POLARIS DATACENTER",
                            "type": "IP DATA SERVICE"
                        }
                    ]
                }
            },
            {
                "Software Standards": {
                    "status": "Error",
                    "result": [
                        {}
                    ],
                    "error": "Dependency failed, no device vendor was acquired."
                }
            },
            {
                "Splunk": {
                    "status": "Success",
                    "result": [
                        {
                            "Number of Entries(within the last 48 hrs)": 1
                        }
                    ]
                }
            }
        ]
    }
]
}